name: gelin
description: A Flutter for random lines generation within a circle area.
version: 0.1.2
homepage: https://github.com/BIX-Digital/gelin

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  logger: ^1.1.0
  quiver: ^3.1.0
  scidart: ^0.0.2-dev.9
  scidart_plot: ^0.0.2-dev.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
